tracker_type: bytetrack
track_high_thresh: 0.5
track_low_thresh: 0.1
new_track_thresh: 0.7
track_buffer: 30
match_thresh: 0.8
gmc_method: none
proximity_thresh: 0.5
appearance_thresh: 0.25
min_box_area: 10
